# Use postgres/example user/password credentials
version: '3.1'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8100:80
    environment:
      PGADMIN_DEFAULT_EMAIL: rinha@rinha.com
      PGADMIN_DEFAULT_PASSWORD: rinha
      PGADMIN_CONFIG_SERVER_MODE: 'False'

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1